# Generated by Django 3.1 on 2020-09-18 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0003_domain_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('MLD', 'Mobile list display'), ('MFD', 'Mobile form display'), ('DLD', 'Desktop list display'), ('DFD', 'Desktop form display')], default=2, max_length=3)),
                ('first_name', models.BooleanField(default=True)),
                ('last_name', models.BooleanField(default=True)),
                ('country', models.BooleanField(default=True)),
                ('name', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=True)),
                ('subject', models.BooleanField(default=True)),
                ('message', models.BooleanField(default=True)),
                ('anything_else', models.BooleanField(default=True)),
                ('sys_created_on', models.DateTimeField(auto_now_add=True)),
                ('sys_updated_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.domain')),
                ('sys_created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_preference_created_by', to=settings.AUTH_USER_MODEL)),
                ('sys_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_preference_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
