# Generated by Django 3.1 on 2020-09-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_preference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainpreference',
            name='domain_path',
            field=models.CharField(default='/', max_length=300),
        ),
    ]
