# Generated by Django 3.1 on 2020-09-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_domain_api_key'),
        ('domain_preference', '0002_domainpreference_domain_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainpreference',
            name='phone_number',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='domainpreference',
            name='device_type',
            field=models.CharField(choices=[('MLD', 'Mobile list display'), ('MFD', 'Mobile form display'), ('DLD', 'Desktop list display'), ('DFD', 'Desktop form display')], default='DLD', max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='domainpreference',
            unique_together={('device_type', 'domain')},
        ),
    ]
