# Generated by Django 3.1 on 2020-09-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
