# Generated by Django 3.1 on 2020-09-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0003_auto_20200917_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
