# Generated by Django 3.1 on 2020-09-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0004_auto_20200917_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
