# Generated by Django 3.1 on 2020-09-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0006_auto_20200926_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
