# Generated by Django 3.1 on 2020-09-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0007_contactform_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactform',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
