# Generated by Django 3.1 on 2020-09-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0008_auto_20200927_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
