# Generated by Django 3.1 on 2020-08-31 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('primary', models.BooleanField(blank=True, default=False, null=True)),
                ('sys_created_on', models.DateTimeField(auto_now_add=True)),
                ('sys_updated_on', models.DateTimeField(auto_now=True)),
                ('domain_code', models.CharField(max_length=6)),
                ('domain_path', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('sp', 'Service Provide'), ('vr', 'Vendor'), ('cr', 'Customer')], default='cr', max_length=2)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.domain')),
            ],
        ),
    ]
