# Generated by Django 3.1 on 2020-09-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_auto_20200916_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='api_key',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
