# Generated by Django 3.1 on 2020-09-16 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_auto_20200916_1554'),
        ('sys_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.domain'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='domain_path',
            field=models.CharField(default='/', max_length=256),
        ),
    ]
