# Generated by Django 3.1 on 2020-09-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_user', '0002_auto_20200916_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='user_type',
            field=models.CharField(choices=[('GU', 'GOOGLE'), ('SU', 'SYSTEM'), ('FU', 'FACEBOOK')], default='SU', max_length=2),
        ),
    ]
