# Generated by Django 3.1 on 2020-09-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_user', '0003_sysuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='is_company_admin',
            field=models.BooleanField(default=False),
        ),
    ]
